### ISSUE TITLE
Some example with kotlin-fu?

### ISSUE THREAD

**Issue by lhenriquegomescamilo** [spring-projects-experimental/spring-security-kotlin-dsl#16]
Hi everyone, I'm trying to use the **kotlin-fu** with the **spring-security-kotlin-dsl**, look my example:

```kotlin
//file: Application.kt
val app = application(WebApplicationType.REACTIVE) {
	enable(dataConfig)
	enable(webConfig)
}

fun main() {
	app.run()
}
```

```kotlin
//file: Configurations.kt
val dataConfig = configuration {
	beans {
		bean<StockMarketRepository>()
	}
	listener<ApplicationReadyEvent> {
		runBlocking {
			ref<StockMarketRepository>().init()
		}
	}

	r2dbcPostgresql() {
		password = "postgres"
		username = "postgres"
		host = "localhost"
		port = 5432

	}
	
}

val webConfig = configuration {

beans {
	bean<StockMarketHandler>()
	bean(::stockMarketRoutes)
	}
	webFlux {
		port = if (profiles.contains("test")) 8181 else 8080
		codecs {
			string()
			jackson()
		}
	}
}
```
... and finally the file of configurarion from spring-security
```kotlin
@EnableWebSecurity
open class SecurityConfig : WebSecurityConfigurerAdapter() {
    override fun configure(http: HttpSecurity?) {
        http {
            authorizeRequests {
                authorize(anyRequest, authenticated)
            }
        }
    }
}
```
I'm right to try to use it that way? I'm very confused in this point, I don't know if I use annotation or use 
inside bean on file **Configuration.kt**

If you show me a little example to solve the specific point,  I can create a PR  with a full example using r2dbc.  🙂

I'm following the example: [kofu-coroutines-r2dbc](https://github.com/spring-projects-experimental/spring-fu/tree/master/samples/kofu-coroutines-r2dbc/src/main/kotlin/com/sample)
Thank's guys!

**Comment by eleftherias** [comment]
@lhenriquegomescamilo 

The sample application you mention is using WebFlux.
A security configuration using `WebSecurityConfigurerAdapter` is for servlet based applications, so it will not work in this example.

To configure security for reactive applications see the [Spring Security reference documentation](https://docs.spring.io/spring-security/site/docs/5.2.2.BUILD-SNAPSHOT/reference/htmlsingle/#reactive-applications).
Although this is not a native Kotiln DSL, you can still use it in Kotlin applications.

WebFlux Security support in the native Kotlin DSL is still in progress.
I have created gh-17 to give more visibility into what is done so far.
