### ISSUE TITLE
Use DSL Marker Annotations to prevent outer scopes leaking into inner ones

### ISSUE THREAD

**Issue by gonozalviii** [spring-projects-experimental/spring-security-kotlin-dsl#19]
Kotlin provides an annotation for preventing scope leaking in DSLs.
Something like this should not be possible:

```
http {
           authorizeRequests {
               authorizeRequests {

               }
           }
        }
```

**Comment by eleftherias** [comment]
@gonozalviii that makes sense to me.

Are you interested in submitting a PR to add this functionality?

If so, I would suggest doing so in the [Spring Security repository](https://github.com/spring-projects/spring-security). Much of the Kotlin DSL code has been ported to that project. If you create the PR, feel free to ping me and I will take a look at it.

**Comment by eleftherias** [comment]
Migrated to https://github.com/spring-projects/spring-security/issues/7971
